package recipe

import (
	"context"
	"errors"
	"fmt"

	coreops "github.com/divisive-ai/vibethis/server/recipe-core/pkg/ops"
	"github.com/google/uuid"
	commonpb "go.temporal.io/api/common/v1"
	enumspb "go.temporal.io/api/enums/v1"
	workflowservice "go.temporal.io/api/workflowservice/v1"
)

// ResetChildWorkflowActivityName is the registered Temporal activity name used by recipe-worker.
const ResetChildWorkflowActivityName = "_internal.recipe.reset_child_workflow"

// ResetChildWorkflowActivityInput captures the reset parameters provided by the parent workflow.
type ResetChildWorkflowActivityInput struct {
	WorkflowID        string `json:"workflow_id"`
	RunID             string `json:"run_id"`
	EventID           int64  `json:"event_id"`
	Reason            string `json:"reason,omitempty"`
	WaitForCompletion bool   `json:"wait_for_completion"`
}

// ResetChildWorkflowActivityResult reports the run id generated by the reset and, when requested,
// the unserialized workflow result.
type ResetChildWorkflowActivityResult struct {
	RunID     string                 `json:"run_id"`
	Completed bool                   `json:"completed"`
	Result    map[string]interface{} `json:"result,omitempty"`
}

// ResetChildWorkflowActivity performs workflow resets using the runtime dependencies supplied by recipe-worker.
type ResetChildWorkflowActivity struct {
	deps coreops.ServiceDependencies2
}

// NewResetChildWorkflowActivity creates a new reset activity bound to the provided dependencies.
func NewResetChildWorkflowActivity(deps coreops.ServiceDependencies2) *ResetChildWorkflowActivity {
	return &ResetChildWorkflowActivity{deps: deps}
}

func (a *ResetChildWorkflowActivity) Execute(ctx context.Context, input ResetChildWorkflowActivityInput) (ResetChildWorkflowActivityResult, error) {
	if input.WorkflowID == "" {
		return ResetChildWorkflowActivityResult{}, errors.New("workflow_id is required")
	}
	if input.RunID == "" {
		return ResetChildWorkflowActivityResult{}, errors.New("run_id is required")
	}
	if input.EventID <= 0 {
		return ResetChildWorkflowActivityResult{}, errors.New("event_id must be positive")
	}
	if a == nil || a.deps == nil {
		return ResetChildWorkflowActivityResult{}, errors.New("dependencies not configured")
	}

	cli, ok := a.deps.WorkflowClient()
	if !ok || cli == nil {
		return ResetChildWorkflowActivityResult{}, errors.New("workflow client dependency not available")
	}
	ns, ok := a.deps.TemporalNamespace()
	if !ok || ns == "" {
		return ResetChildWorkflowActivityResult{}, errors.New("temporal namespace not configured")
	}

	resetReq := &workflowservice.ResetWorkflowExecutionRequest{
		Namespace: ns,
		WorkflowExecution: &commonpb.WorkflowExecution{
			WorkflowId: input.WorkflowID,
			RunId:      input.RunID,
		},
		Reason:                    input.Reason,
		WorkflowTaskFinishEventId: input.EventID,
		RequestId:                 uuid.NewString(),
		ResetReapplyType:          enumspb.RESET_REAPPLY_TYPE_SIGNAL,
	}

	resp, err := cli.WorkflowService().ResetWorkflowExecution(ctx, resetReq)
	if err != nil {
		return ResetChildWorkflowActivityResult{}, err
	}

	newRunID := resp.GetRunId()
	if newRunID == "" {
		// Temporal should always return a run id, but fall back to the supplied value if it does not.
		newRunID = input.RunID
	}

	result := ResetChildWorkflowActivityResult{RunID: newRunID}
	if !input.WaitForCompletion {
		return result, nil
	}

	// Wait for the reset run to complete and hydrate the result payload.
	workflowRun := cli.GetWorkflow(ctx, input.WorkflowID, newRunID)
	if workflowRun == nil {
		return ResetChildWorkflowActivityResult{}, fmt.Errorf("failed to obtain workflow handle for %s/%s", input.WorkflowID, newRunID)
	}

	var payload map[string]interface{}
	if err := workflowRun.Get(ctx, &payload); err != nil {
		return ResetChildWorkflowActivityResult{}, err
	}
	if payload == nil {
		payload = make(map[string]interface{})
	}
	result.Completed = true
	result.Result = payload
	return result, nil
}
