// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package devcontainer

import "encoding/json"
import "errors"
import "fmt"
import "reflect"
import "regexp"

type BuildOptions struct {
	// Build arguments.
	Args map[string]string `json:"args,omitempty" yaml:"args,omitempty" mapstructure:"args,omitempty"`

	// The image to consider as a cache. Use an array to specify multiple images.
	CacheFrom interface{} `json:"cacheFrom,omitempty" yaml:"cacheFrom,omitempty" mapstructure:"cacheFrom,omitempty"`

	// Additional arguments passed to the build command.
	Options []string `json:"options,omitempty" yaml:"options,omitempty" mapstructure:"options,omitempty"`

	// Target stage in a multi-stage build.
	Target *string `json:"target,omitempty" yaml:"target,omitempty" mapstructure:"target,omitempty"`
}

type ComposeContainer struct {
	// The name of the docker-compose file(s) used to start the services.
	DockerComposeFile interface{} `json:"dockerComposeFile" yaml:"dockerComposeFile" mapstructure:"dockerComposeFile"`

	// Whether to overwrite the command specified in the image. The default is false.
	OverrideCommand *bool `json:"overrideCommand,omitempty" yaml:"overrideCommand,omitempty" mapstructure:"overrideCommand,omitempty"`

	// An array of services that should be started and stopped.
	RunServices []string `json:"runServices,omitempty" yaml:"runServices,omitempty" mapstructure:"runServices,omitempty"`

	// The service you want to work on. This is considered the primary container for
	// your dev environment which your editor will connect to.
	Service string `json:"service" yaml:"service" mapstructure:"service"`

	// Action to take when the user disconnects from the primary container in their
	// editor. The default is to stop all of the compose containers.
	ShutdownAction *ComposeContainerShutdownAction `json:"shutdownAction,omitempty" yaml:"shutdownAction,omitempty" mapstructure:"shutdownAction,omitempty"`

	// The path of the workspace folder inside the container. This is typically the
	// target path of a volume mount in the docker-compose.yml.
	WorkspaceFolder string `json:"workspaceFolder" yaml:"workspaceFolder" mapstructure:"workspaceFolder"`
}

type ComposeContainerShutdownAction string

const ComposeContainerShutdownActionNone ComposeContainerShutdownAction = "none"
const ComposeContainerShutdownActionStopCompose ComposeContainerShutdownAction = "stopCompose"

var enumValues_ComposeContainerShutdownAction = []interface{}{
	"none",
	"stopCompose",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ComposeContainerShutdownAction) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ComposeContainerShutdownAction {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ComposeContainerShutdownAction, v)
	}
	*j = ComposeContainerShutdownAction(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ComposeContainer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dockerComposeFile"]; raw != nil && !ok {
		return fmt.Errorf("field dockerComposeFile in ComposeContainer: required")
	}
	if _, ok := raw["service"]; raw != nil && !ok {
		return fmt.Errorf("field service in ComposeContainer: required")
	}
	if _, ok := raw["workspaceFolder"]; raw != nil && !ok {
		return fmt.Errorf("field workspaceFolder in ComposeContainer: required")
	}
	type Plain ComposeContainer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ComposeContainer(plain)
	return nil
}

type DevContainerCommon struct {
	// The JSON schema of the `devcontainer.json` file.
	Schema *string `json:"$schema,omitempty" yaml:"$schema,omitempty" mapstructure:"$schema,omitempty"`

	// AdditionalProperties corresponds to the JSON schema field
	// "additionalProperties".
	AdditionalProperties map[string]interface{} `json:"additionalProperties,omitempty" yaml:"additionalProperties,omitempty" mapstructure:"additionalProperties,omitempty"`

	// Passes docker capabilities to include when creating the dev container.
	CapAdd []string `json:"capAdd,omitempty" yaml:"capAdd,omitempty" mapstructure:"capAdd,omitempty"`

	// Container environment variables.
	ContainerEnv map[string]string `json:"containerEnv,omitempty" yaml:"containerEnv,omitempty" mapstructure:"containerEnv,omitempty"`

	// The user the container will be started with. The default is the user on the
	// Docker image.
	ContainerUser *string `json:"containerUser,omitempty" yaml:"containerUser,omitempty" mapstructure:"containerUser,omitempty"`

	// Tool-specific configuration. Each tool should use a JSON object subproperty
	// with a unique name to group its customizations.
	Customizations map[string]interface{} `json:"customizations,omitempty" yaml:"customizations,omitempty" mapstructure:"customizations,omitempty"`

	// Features to add to the dev container.
	Features *DevContainerCommonFeatures `json:"features,omitempty" yaml:"features,omitempty" mapstructure:"features,omitempty"`

	// Ports that are forwarded from the container to the local machine. Can be an
	// integer port number, or a string of the format "host:port_number".
	ForwardPorts []interface{} `json:"forwardPorts,omitempty" yaml:"forwardPorts,omitempty" mapstructure:"forwardPorts,omitempty"`

	// Host hardware requirements.
	HostRequirements *DevContainerCommonHostRequirements `json:"hostRequirements,omitempty" yaml:"hostRequirements,omitempty" mapstructure:"hostRequirements,omitempty"`

	// Passes the --init flag when creating the dev container.
	Init *bool `json:"init,omitempty" yaml:"init,omitempty" mapstructure:"init,omitempty"`

	// A command to run locally (i.e Your host machine, cloud VM) before anything
	// else. This command is run before "onCreateCommand". If this is a single string,
	// it will be run in a shell. If this is an array of strings, it will be run as a
	// single command without shell. If this is an object, each provided command will
	// be run in parallel.
	InitializeCommand interface{} `json:"initializeCommand,omitempty" yaml:"initializeCommand,omitempty" mapstructure:"initializeCommand,omitempty"`

	// Mount points to set up when creating the container. See Docker's documentation
	// for the --mount option for the supported syntax.
	Mounts []DevContainerCommonMountsElem `json:"mounts,omitempty" yaml:"mounts,omitempty" mapstructure:"mounts,omitempty"`

	// A name for the dev container which can be displayed to the user.
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// A command to run when creating the container. This command is run after
	// "initializeCommand" and before "updateContentCommand". If this is a single
	// string, it will be run in a shell. If this is an array of strings, it will be
	// run as a single command without shell. If this is an object, each provided
	// command will be run in parallel.
	OnCreateCommand interface{} `json:"onCreateCommand,omitempty" yaml:"onCreateCommand,omitempty" mapstructure:"onCreateCommand,omitempty"`

	// OtherPortsAttributes corresponds to the JSON schema field
	// "otherPortsAttributes".
	OtherPortsAttributes *DevContainerCommonOtherPortsAttributes `json:"otherPortsAttributes,omitempty" yaml:"otherPortsAttributes,omitempty" mapstructure:"otherPortsAttributes,omitempty"`

	// Array consisting of the Feature id (without the semantic version) of Features
	// in the order the user wants them to be installed.
	OverrideFeatureInstallOrder []string `json:"overrideFeatureInstallOrder,omitempty" yaml:"overrideFeatureInstallOrder,omitempty" mapstructure:"overrideFeatureInstallOrder,omitempty"`

	// PortsAttributes corresponds to the JSON schema field "portsAttributes".
	PortsAttributes map[string]interface{} `json:"portsAttributes,omitempty" yaml:"portsAttributes,omitempty" mapstructure:"portsAttributes,omitempty"`

	// A command to run when attaching to the container. This command is run after
	// "postStartCommand". If this is a single string, it will be run in a shell. If
	// this is an array of strings, it will be run as a single command without shell.
	// If this is an object, each provided command will be run in parallel.
	PostAttachCommand interface{} `json:"postAttachCommand,omitempty" yaml:"postAttachCommand,omitempty" mapstructure:"postAttachCommand,omitempty"`

	// A command to run after creating the container. This command is run after
	// "updateContentCommand" and before "postStartCommand". If this is a single
	// string, it will be run in a shell. If this is an array of strings, it will be
	// run as a single command without shell. If this is an object, each provided
	// command will be run in parallel.
	PostCreateCommand interface{} `json:"postCreateCommand,omitempty" yaml:"postCreateCommand,omitempty" mapstructure:"postCreateCommand,omitempty"`

	// A command to run after starting the container. This command is run after
	// "postCreateCommand" and before "postAttachCommand". If this is a single string,
	// it will be run in a shell. If this is an array of strings, it will be run as a
	// single command without shell. If this is an object, each provided command will
	// be run in parallel.
	PostStartCommand interface{} `json:"postStartCommand,omitempty" yaml:"postStartCommand,omitempty" mapstructure:"postStartCommand,omitempty"`

	// Passes the --privileged flag when creating the dev container.
	Privileged *bool `json:"privileged,omitempty" yaml:"privileged,omitempty" mapstructure:"privileged,omitempty"`

	// Remote environment variables to set for processes spawned in the container
	// including lifecycle scripts and any remote editor/IDE server process.
	RemoteEnv map[string]*string `json:"remoteEnv,omitempty" yaml:"remoteEnv,omitempty" mapstructure:"remoteEnv,omitempty"`

	// The username to use for spawning processes in the container including lifecycle
	// scripts and any remote editor/IDE server process. The default is the same user
	// as the container.
	RemoteUser *string `json:"remoteUser,omitempty" yaml:"remoteUser,omitempty" mapstructure:"remoteUser,omitempty"`

	// Recommended secrets for this dev container. Recommendations are provided as
	// environment variable keys with optional metadata.
	Secrets map[string]interface{} `json:"secrets,omitempty" yaml:"secrets,omitempty" mapstructure:"secrets,omitempty"`

	// Passes docker security options to include when creating the dev container.
	SecurityOpt []string `json:"securityOpt,omitempty" yaml:"securityOpt,omitempty" mapstructure:"securityOpt,omitempty"`

	// A command to run when creating the container and rerun when the workspace
	// content was updated while creating the container. This command is run after
	// "onCreateCommand" and before "postCreateCommand". If this is a single string,
	// it will be run in a shell. If this is an array of strings, it will be run as a
	// single command without shell. If this is an object, each provided command will
	// be run in parallel.
	UpdateContentCommand interface{} `json:"updateContentCommand,omitempty" yaml:"updateContentCommand,omitempty" mapstructure:"updateContentCommand,omitempty"`

	// Controls whether on Linux the container's user should be updated with the local
	// user's UID and GID. On by default when opening from a local folder.
	UpdateRemoteUserUID *bool `json:"updateRemoteUserUID,omitempty" yaml:"updateRemoteUserUID,omitempty" mapstructure:"updateRemoteUserUID,omitempty"`

	// User environment probe to run. The default is "loginInteractiveShell".
	UserEnvProbe *DevContainerCommonUserEnvProbe `json:"userEnvProbe,omitempty" yaml:"userEnvProbe,omitempty" mapstructure:"userEnvProbe,omitempty"`

	// The user command to wait for before continuing execution in the background
	// while the UI is starting up. The default is "updateContentCommand".
	WaitFor *DevContainerCommonWaitFor `json:"waitFor,omitempty" yaml:"waitFor,omitempty" mapstructure:"waitFor,omitempty"`
}

// Features to add to the dev container.
type DevContainerCommonFeatures struct {
	// Fish corresponds to the JSON schema field "fish".
	Fish interface{} `json:"fish,omitempty" yaml:"fish,omitempty" mapstructure:"fish,omitempty"`

	// Gradle corresponds to the JSON schema field "gradle".
	Gradle interface{} `json:"gradle,omitempty" yaml:"gradle,omitempty" mapstructure:"gradle,omitempty"`

	// Homebrew corresponds to the JSON schema field "homebrew".
	Homebrew interface{} `json:"homebrew,omitempty" yaml:"homebrew,omitempty" mapstructure:"homebrew,omitempty"`

	// Jupyterlab corresponds to the JSON schema field "jupyterlab".
	Jupyterlab interface{} `json:"jupyterlab,omitempty" yaml:"jupyterlab,omitempty" mapstructure:"jupyterlab,omitempty"`

	// Maven corresponds to the JSON schema field "maven".
	Maven interface{} `json:"maven,omitempty" yaml:"maven,omitempty" mapstructure:"maven,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// Host hardware requirements.
type DevContainerCommonHostRequirements struct {
	// Number of required CPUs.
	Cpus *int `json:"cpus,omitempty" yaml:"cpus,omitempty" mapstructure:"cpus,omitempty"`

	// Gpu corresponds to the JSON schema field "gpu".
	Gpu interface{} `json:"gpu,omitempty" yaml:"gpu,omitempty" mapstructure:"gpu,omitempty"`

	// Amount of required RAM in bytes. Supports units tb, gb, mb and kb.
	Memory *string `json:"memory,omitempty" yaml:"memory,omitempty" mapstructure:"memory,omitempty"`

	// Amount of required disk space in bytes. Supports units tb, gb, mb and kb.
	Storage *string `json:"storage,omitempty" yaml:"storage,omitempty" mapstructure:"storage,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DevContainerCommonHostRequirements) UnmarshalJSON(value []byte) error {
	type Plain DevContainerCommonHostRequirements
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Cpus != nil && 1 > *plain.Cpus {
		return fmt.Errorf("field %s: must be >= %v", "cpus", 1)
	}
	if plain.Memory != nil {
		if matched, _ := regexp.MatchString(`^\d+([tgmk]b)?$`, string(*plain.Memory)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "Memory", `^\d+([tgmk]b)?$`)
		}
	}
	if plain.Storage != nil {
		if matched, _ := regexp.MatchString(`^\d+([tgmk]b)?$`, string(*plain.Storage)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "Storage", `^\d+([tgmk]b)?$`)
		}
	}
	*j = DevContainerCommonHostRequirements(plain)
	return nil
}

type DevContainerCommonMountsElem struct {
	// Mount source.
	Source *string `json:"source,omitempty" yaml:"source,omitempty" mapstructure:"source,omitempty"`

	// Mount target.
	Target string `json:"target" yaml:"target" mapstructure:"target"`

	// Mount type.
	Type MountType `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DevContainerCommonMountsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var devContainerCommonMountsElem_0 DevContainerCommonMountsElem_0
	var devContainerCommonMountsElem_1 DevContainerCommonMountsElem_1
	var errs []error
	if err := devContainerCommonMountsElem_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if err := devContainerCommonMountsElem_1.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 2 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain DevContainerCommonMountsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DevContainerCommonMountsElem(plain)
	return nil
}

type DevContainerCommonOtherPortsAttributes struct {
	// Automatically prompt for elevation (if needed) when this port is forwarded.
	// Elevate is required if the local port is a privileged port.
	ElevateIfNeeded bool `json:"elevateIfNeeded,omitempty" yaml:"elevateIfNeeded,omitempty" mapstructure:"elevateIfNeeded,omitempty"`

	// Label that will be shown in the UI for this port.
	Label string `json:"label,omitempty" yaml:"label,omitempty" mapstructure:"label,omitempty"`

	// Defines the action that occurs when the port is discovered for automatic
	// forwarding
	OnAutoForward DevContainerCommonOtherPortsAttributesOnAutoForward `json:"onAutoForward,omitempty" yaml:"onAutoForward,omitempty" mapstructure:"onAutoForward,omitempty"`

	// The protocol to use when forwarding this port.
	Protocol *DevContainerCommonOtherPortsAttributesProtocol `json:"protocol,omitempty" yaml:"protocol,omitempty" mapstructure:"protocol,omitempty"`

	// RequireLocalPort corresponds to the JSON schema field "requireLocalPort".
	RequireLocalPort bool `json:"requireLocalPort,omitempty" yaml:"requireLocalPort,omitempty" mapstructure:"requireLocalPort,omitempty"`
}

type DevContainerCommonOtherPortsAttributesOnAutoForward string

const DevContainerCommonOtherPortsAttributesOnAutoForwardIgnore DevContainerCommonOtherPortsAttributesOnAutoForward = "ignore"
const DevContainerCommonOtherPortsAttributesOnAutoForwardNotify DevContainerCommonOtherPortsAttributesOnAutoForward = "notify"
const DevContainerCommonOtherPortsAttributesOnAutoForwardOpenBrowser DevContainerCommonOtherPortsAttributesOnAutoForward = "openBrowser"
const DevContainerCommonOtherPortsAttributesOnAutoForwardOpenPreview DevContainerCommonOtherPortsAttributesOnAutoForward = "openPreview"
const DevContainerCommonOtherPortsAttributesOnAutoForwardSilent DevContainerCommonOtherPortsAttributesOnAutoForward = "silent"

var enumValues_DevContainerCommonOtherPortsAttributesOnAutoForward = []interface{}{
	"notify",
	"openBrowser",
	"openPreview",
	"silent",
	"ignore",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DevContainerCommonOtherPortsAttributesOnAutoForward) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DevContainerCommonOtherPortsAttributesOnAutoForward {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_DevContainerCommonOtherPortsAttributesOnAutoForward, v)
	}
	*j = DevContainerCommonOtherPortsAttributesOnAutoForward(v)
	return nil
}

type DevContainerCommonOtherPortsAttributesProtocol string

const DevContainerCommonOtherPortsAttributesProtocolHttp DevContainerCommonOtherPortsAttributesProtocol = "http"
const DevContainerCommonOtherPortsAttributesProtocolHttps DevContainerCommonOtherPortsAttributesProtocol = "https"

var enumValues_DevContainerCommonOtherPortsAttributesProtocol = []interface{}{
	"http",
	"https",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DevContainerCommonOtherPortsAttributesProtocol) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DevContainerCommonOtherPortsAttributesProtocol {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_DevContainerCommonOtherPortsAttributesProtocol, v)
	}
	*j = DevContainerCommonOtherPortsAttributesProtocol(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DevContainerCommonOtherPortsAttributes) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain DevContainerCommonOtherPortsAttributes
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["elevateIfNeeded"]; !ok || v == nil {
		plain.ElevateIfNeeded = false
	}
	if v, ok := raw["label"]; !ok || v == nil {
		plain.Label = "Application"
	}
	if v, ok := raw["onAutoForward"]; !ok || v == nil {
		plain.OnAutoForward = "notify"
	}
	if v, ok := raw["requireLocalPort"]; !ok || v == nil {
		plain.RequireLocalPort = false
	}
	*j = DevContainerCommonOtherPortsAttributes(plain)
	return nil
}

type DevContainerCommonUserEnvProbe string

const DevContainerCommonUserEnvProbeInteractiveShell DevContainerCommonUserEnvProbe = "interactiveShell"
const DevContainerCommonUserEnvProbeLoginInteractiveShell DevContainerCommonUserEnvProbe = "loginInteractiveShell"
const DevContainerCommonUserEnvProbeLoginShell DevContainerCommonUserEnvProbe = "loginShell"
const DevContainerCommonUserEnvProbeNone DevContainerCommonUserEnvProbe = "none"

var enumValues_DevContainerCommonUserEnvProbe = []interface{}{
	"none",
	"loginShell",
	"loginInteractiveShell",
	"interactiveShell",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DevContainerCommonUserEnvProbe) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DevContainerCommonUserEnvProbe {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_DevContainerCommonUserEnvProbe, v)
	}
	*j = DevContainerCommonUserEnvProbe(v)
	return nil
}

type DevContainerCommonWaitFor string

const DevContainerCommonWaitForInitializeCommand DevContainerCommonWaitFor = "initializeCommand"
const DevContainerCommonWaitForOnCreateCommand DevContainerCommonWaitFor = "onCreateCommand"
const DevContainerCommonWaitForPostCreateCommand DevContainerCommonWaitFor = "postCreateCommand"
const DevContainerCommonWaitForPostStartCommand DevContainerCommonWaitFor = "postStartCommand"
const DevContainerCommonWaitForUpdateContentCommand DevContainerCommonWaitFor = "updateContentCommand"

var enumValues_DevContainerCommonWaitFor = []interface{}{
	"initializeCommand",
	"onCreateCommand",
	"updateContentCommand",
	"postCreateCommand",
	"postStartCommand",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DevContainerCommonWaitFor) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DevContainerCommonWaitFor {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_DevContainerCommonWaitFor, v)
	}
	*j = DevContainerCommonWaitFor(v)
	return nil
}

type DockerfileContainer interface{}

type ImageContainer struct {
	// The docker image that will be used to create the container.
	Image string `json:"image" yaml:"image" mapstructure:"image"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ImageContainer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["image"]; raw != nil && !ok {
		return fmt.Errorf("field image in ImageContainer: required")
	}
	type Plain ImageContainer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ImageContainer(plain)
	return nil
}

type Mount struct {
	// Mount source.
	Source *string `json:"source,omitempty" yaml:"source,omitempty" mapstructure:"source,omitempty"`

	// Mount target.
	Target string `json:"target" yaml:"target" mapstructure:"target"`

	// Mount type.
	Type MountType `json:"type" yaml:"type" mapstructure:"type"`
}

type MountType string

const MountTypeBind MountType = "bind"
const MountTypeVolume MountType = "volume"

var enumValues_MountType = []interface{}{
	"bind",
	"volume",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Mount) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["target"]; raw != nil && !ok {
		return fmt.Errorf("field target in Mount: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Mount: required")
	}
	type Plain Mount
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Mount(plain)
	return nil
}

type DevContainerCommonMountsElem_0 = Mount
type DevContainerCommonMountsElem_1 = Mount

// UnmarshalJSON implements json.Unmarshaler.
func (j *MountType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MountType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MountType, v)
	}
	*j = MountType(v)
	return nil
}

type NonComposeBase struct {
	// Application ports that are exposed by the container. This can be a single port
	// or an array of ports. Each port can be a number or a string. A number is mapped
	// to the same port on the host. A string is passed to Docker unchanged and can be
	// used to map ports differently, e.g. "8000:8010".
	AppPort interface{} `json:"appPort,omitempty" yaml:"appPort,omitempty" mapstructure:"appPort,omitempty"`

	// Whether to overwrite the command specified in the image. The default is true.
	OverrideCommand *bool `json:"overrideCommand,omitempty" yaml:"overrideCommand,omitempty" mapstructure:"overrideCommand,omitempty"`

	// The arguments required when starting in the container.
	RunArgs []string `json:"runArgs,omitempty" yaml:"runArgs,omitempty" mapstructure:"runArgs,omitempty"`

	// Action to take when the user disconnects from the container in their editor.
	// The default is to stop the container.
	ShutdownAction *NonComposeBaseShutdownAction `json:"shutdownAction,omitempty" yaml:"shutdownAction,omitempty" mapstructure:"shutdownAction,omitempty"`

	// The path of the workspace folder inside the container.
	WorkspaceFolder *string `json:"workspaceFolder,omitempty" yaml:"workspaceFolder,omitempty" mapstructure:"workspaceFolder,omitempty"`

	// The --mount parameter for docker run. The default is to mount the project
	// folder at /workspaces/$project.
	WorkspaceMount *string `json:"workspaceMount,omitempty" yaml:"workspaceMount,omitempty" mapstructure:"workspaceMount,omitempty"`
}

type NonComposeBaseShutdownAction string

const NonComposeBaseShutdownActionNone NonComposeBaseShutdownAction = "none"
const NonComposeBaseShutdownActionStopContainer NonComposeBaseShutdownAction = "stopContainer"

var enumValues_NonComposeBaseShutdownAction = []interface{}{
	"none",
	"stopContainer",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NonComposeBaseShutdownAction) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NonComposeBaseShutdownAction {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NonComposeBaseShutdownAction, v)
	}
	*j = NonComposeBaseShutdownAction(v)
	return nil
}
