// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ContainerStatus.
const (
	Error   ContainerStatus = "error"
	None    ContainerStatus = "none"
	Running ContainerStatus = "running"
	Stopped ContainerStatus = "stopped"
)

// Defines values for GitStatusFileStatus.
const (
	A     GitStatusFileStatus = "A"
	C     GitStatusFileStatus = "C"
	D     GitStatusFileStatus = "D"
	Empty GitStatusFileStatus = "?"
	M     GitStatusFileStatus = "M"
	R     GitStatusFileStatus = "R"
	U     GitStatusFileStatus = "U"
)

// Cell defines model for Cell.
type Cell struct {
	// Dependencies List of cell IDs this cell depends on
	Dependencies []string `json:"dependencies"`

	// Id Unique identifier for the cell
	Id string `json:"id"`

	// Name Display name of the cell
	Name string `json:"name"`

	// Path File system path to the cell directory
	Path string `json:"path"`

	// Type Type of cell (e.g., module, library)
	Type string `json:"type"`
}

// ContainerStatus Current container status
type ContainerStatus string

// Edge defines model for Edge.
type Edge struct {
	// Id Unique identifier for the edge
	Id string `json:"id"`

	// Source Cell ID of the source (from)
	Source string `json:"source"`

	// Target Cell ID of the target (to)
	Target string `json:"target"`
}

// FileInfo defines model for FileInfo.
type FileInfo struct {
	// IsDir Whether this is a directory
	IsDir bool `json:"isDir"`

	// Name File or directory name
	Name string `json:"name"`

	// Path Relative path from cell directory
	Path string `json:"path"`

	// Size File size in bytes (0 for directories)
	Size int64 `json:"size"`

	// Type File type or MIME type
	Type string `json:"type"`
}

// GitCommit defines model for GitCommit.
type GitCommit struct {
	// Author Commit author name and email
	Author string `json:"author"`

	// Date Commit timestamp
	Date time.Time `json:"date"`

	// Hash Full commit hash
	Hash string `json:"hash"`

	// Message Commit message
	Message string `json:"message"`

	// ShortHash Abbreviated commit hash
	ShortHash string `json:"shortHash"`
}

// GitStatus defines model for GitStatus.
type GitStatus struct {
	// Ahead Number of commits ahead of remote
	Ahead int `json:"ahead"`

	// Behind Number of commits behind remote
	Behind int `json:"behind"`

	// Branch Current Git branch name
	Branch string `json:"branch"`

	// Clean Whether the working directory is clean
	Clean bool `json:"clean"`

	// Files List of modified files
	Files []GitStatusFile `json:"files"`

	// HasRemote Whether a remote is configured
	HasRemote bool `json:"hasRemote"`
}

// GitStatusFile defines model for GitStatusFile.
type GitStatusFile struct {
	// Path File path relative to repository root
	Path string `json:"path"`

	// Status Git status code (M=modified, A=added, D=deleted, ?=untracked, etc.)
	Status GitStatusFileStatus `json:"status"`
}

// GitStatusFileStatus Git status code (M=modified, A=added, D=deleted, ?=untracked, etc.)
type GitStatusFileStatus string

// Graph defines model for Graph.
type Graph struct {
	// Cells List of all cells in the graph
	Cells []Cell `json:"cells"`

	// Edges List of all edges (dependencies) in the graph
	Edges []Edge `json:"edges"`
}

// Position defines model for Position.
type Position struct {
	// CellId ID of the cell this position belongs to
	CellId string `json:"cellId"`

	// X X coordinate in the UI
	X float64 `json:"x"`

	// Y Y coordinate in the UI
	Y float64 `json:"y"`
}

// UpdateDevcontainerJSONBody defines parameters for UpdateDevcontainer.
type UpdateDevcontainerJSONBody struct {
	// Content JSON content for the devcontainer.json file
	Content string `json:"content"`
}

// ListCellFilesParams defines parameters for ListCellFiles.
type ListCellFilesParams struct {
	// Path Subdirectory path within the cell (optional)
	Path *string `form:"path,omitempty" json:"path,omitempty"`
}

// WriteCellFileJSONBody defines parameters for WriteCellFile.
type WriteCellFileJSONBody struct {
	// Content The content to write to the file
	Content string `json:"content"`
}

// CreateGitCommitJSONBody defines parameters for CreateGitCommit.
type CreateGitCommitJSONBody struct {
	// Files Optional list of files to stage before committing
	Files *[]string `json:"files,omitempty"`

	// Message Commit message
	Message string `json:"message"`
}

// GetGitDiffParams defines parameters for GetGitDiff.
type GetGitDiffParams struct {
	// Staged Whether to show staged changes only
	Staged *bool `form:"staged,omitempty" json:"staged,omitempty"`
}

// GetGitHistoryParams defines parameters for GetGitHistory.
type GetGitHistoryParams struct {
	// Limit Maximum number of commits to retrieve
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// SavePositionsJSONBody defines parameters for SavePositions.
type SavePositionsJSONBody = []Position

// UpdateDevcontainerJSONRequestBody defines body for UpdateDevcontainer for application/json ContentType.
type UpdateDevcontainerJSONRequestBody UpdateDevcontainerJSONBody

// WriteCellFileJSONRequestBody defines body for WriteCellFile for application/json ContentType.
type WriteCellFileJSONRequestBody WriteCellFileJSONBody

// CreateGitCommitJSONRequestBody defines body for CreateGitCommit for application/json ContentType.
type CreateGitCommitJSONRequestBody CreateGitCommitJSONBody

// SavePositionsJSONRequestBody defines body for SavePositions for application/json ContentType.
type SavePositionsJSONRequestBody = SavePositionsJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateContainer request
	CreateContainer(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateDevcontainerWithBody request with any body
	UpdateDevcontainerWithBody(ctx context.Context, cellId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateDevcontainer(ctx context.Context, cellId string, body UpdateDevcontainerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ResetContainer request
	ResetContainer(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RestartContainer request
	RestartContainer(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartContainer request
	StartContainer(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetContainerStatus request
	GetContainerStatus(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StopContainer request
	StopContainer(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListCellFiles request
	ListCellFiles(ctx context.Context, cellId string, params *ListCellFilesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReadCellFile request
	ReadCellFile(ctx context.Context, cellId string, filePath string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// WriteCellFileWithBody request with any body
	WriteCellFileWithBody(ctx context.Context, cellId string, filePath string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	WriteCellFile(ctx context.Context, cellId string, filePath string, body WriteCellFileJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateGitCommitWithBody request with any body
	CreateGitCommitWithBody(ctx context.Context, cellId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateGitCommit(ctx context.Context, cellId string, body CreateGitCommitJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGitDiff request
	GetGitDiff(ctx context.Context, cellId string, params *GetGitDiffParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGitHistory request
	GetGitHistory(ctx context.Context, cellId string, params *GetGitHistoryParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGitStatus request
	GetGitStatus(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGraph request
	GetGraph(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPositions request
	GetPositions(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SavePositionsWithBody request with any body
	SavePositionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SavePositions(ctx context.Context, body SavePositionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateContainer(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateContainerRequest(c.Server, cellId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateDevcontainerWithBody(ctx context.Context, cellId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDevcontainerRequestWithBody(c.Server, cellId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateDevcontainer(ctx context.Context, cellId string, body UpdateDevcontainerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDevcontainerRequest(c.Server, cellId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResetContainer(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResetContainerRequest(c.Server, cellId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RestartContainer(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRestartContainerRequest(c.Server, cellId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartContainer(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartContainerRequest(c.Server, cellId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetContainerStatus(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetContainerStatusRequest(c.Server, cellId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StopContainer(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStopContainerRequest(c.Server, cellId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListCellFiles(ctx context.Context, cellId string, params *ListCellFilesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCellFilesRequest(c.Server, cellId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReadCellFile(ctx context.Context, cellId string, filePath string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReadCellFileRequest(c.Server, cellId, filePath)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) WriteCellFileWithBody(ctx context.Context, cellId string, filePath string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWriteCellFileRequestWithBody(c.Server, cellId, filePath, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) WriteCellFile(ctx context.Context, cellId string, filePath string, body WriteCellFileJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWriteCellFileRequest(c.Server, cellId, filePath, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateGitCommitWithBody(ctx context.Context, cellId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateGitCommitRequestWithBody(c.Server, cellId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateGitCommit(ctx context.Context, cellId string, body CreateGitCommitJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateGitCommitRequest(c.Server, cellId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGitDiff(ctx context.Context, cellId string, params *GetGitDiffParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGitDiffRequest(c.Server, cellId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGitHistory(ctx context.Context, cellId string, params *GetGitHistoryParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGitHistoryRequest(c.Server, cellId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGitStatus(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGitStatusRequest(c.Server, cellId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGraph(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGraphRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPositions(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPositionsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SavePositionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSavePositionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SavePositions(ctx context.Context, body SavePositionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSavePositionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateContainerRequest generates requests for CreateContainer
func NewCreateContainerRequest(server string, cellId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cellId", runtime.ParamLocationPath, cellId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cells/%s/container/create", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateDevcontainerRequest calls the generic UpdateDevcontainer builder with application/json body
func NewUpdateDevcontainerRequest(server string, cellId string, body UpdateDevcontainerJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateDevcontainerRequestWithBody(server, cellId, "application/json", bodyReader)
}

// NewUpdateDevcontainerRequestWithBody generates requests for UpdateDevcontainer with any type of body
func NewUpdateDevcontainerRequestWithBody(server string, cellId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cellId", runtime.ParamLocationPath, cellId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cells/%s/container/devcontainer", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewResetContainerRequest generates requests for ResetContainer
func NewResetContainerRequest(server string, cellId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cellId", runtime.ParamLocationPath, cellId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cells/%s/container/reset", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRestartContainerRequest generates requests for RestartContainer
func NewRestartContainerRequest(server string, cellId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cellId", runtime.ParamLocationPath, cellId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cells/%s/container/restart", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStartContainerRequest generates requests for StartContainer
func NewStartContainerRequest(server string, cellId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cellId", runtime.ParamLocationPath, cellId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cells/%s/container/start", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetContainerStatusRequest generates requests for GetContainerStatus
func NewGetContainerStatusRequest(server string, cellId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cellId", runtime.ParamLocationPath, cellId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cells/%s/container/status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStopContainerRequest generates requests for StopContainer
func NewStopContainerRequest(server string, cellId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cellId", runtime.ParamLocationPath, cellId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cells/%s/container/stop", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListCellFilesRequest generates requests for ListCellFiles
func NewListCellFilesRequest(server string, cellId string, params *ListCellFilesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cellId", runtime.ParamLocationPath, cellId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cells/%s/files", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Path != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "path", runtime.ParamLocationQuery, *params.Path); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReadCellFileRequest generates requests for ReadCellFile
func NewReadCellFileRequest(server string, cellId string, filePath string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cellId", runtime.ParamLocationPath, cellId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "filePath", runtime.ParamLocationPath, filePath)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cells/%s/files/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewWriteCellFileRequest calls the generic WriteCellFile builder with application/json body
func NewWriteCellFileRequest(server string, cellId string, filePath string, body WriteCellFileJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewWriteCellFileRequestWithBody(server, cellId, filePath, "application/json", bodyReader)
}

// NewWriteCellFileRequestWithBody generates requests for WriteCellFile with any type of body
func NewWriteCellFileRequestWithBody(server string, cellId string, filePath string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cellId", runtime.ParamLocationPath, cellId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "filePath", runtime.ParamLocationPath, filePath)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cells/%s/files/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateGitCommitRequest calls the generic CreateGitCommit builder with application/json body
func NewCreateGitCommitRequest(server string, cellId string, body CreateGitCommitJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateGitCommitRequestWithBody(server, cellId, "application/json", bodyReader)
}

// NewCreateGitCommitRequestWithBody generates requests for CreateGitCommit with any type of body
func NewCreateGitCommitRequestWithBody(server string, cellId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cellId", runtime.ParamLocationPath, cellId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cells/%s/git/commit", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetGitDiffRequest generates requests for GetGitDiff
func NewGetGitDiffRequest(server string, cellId string, params *GetGitDiffParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cellId", runtime.ParamLocationPath, cellId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cells/%s/git/diff", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Staged != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "staged", runtime.ParamLocationQuery, *params.Staged); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetGitHistoryRequest generates requests for GetGitHistory
func NewGetGitHistoryRequest(server string, cellId string, params *GetGitHistoryParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cellId", runtime.ParamLocationPath, cellId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cells/%s/git/history", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetGitStatusRequest generates requests for GetGitStatus
func NewGetGitStatusRequest(server string, cellId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cellId", runtime.ParamLocationPath, cellId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/cells/%s/git/status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetGraphRequest generates requests for GetGraph
func NewGetGraphRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/graph")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPositionsRequest generates requests for GetPositions
func NewGetPositionsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/positions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSavePositionsRequest calls the generic SavePositions builder with application/json body
func NewSavePositionsRequest(server string, body SavePositionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSavePositionsRequestWithBody(server, "application/json", bodyReader)
}

// NewSavePositionsRequestWithBody generates requests for SavePositions with any type of body
func NewSavePositionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/positions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateContainerWithResponse request
	CreateContainerWithResponse(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*CreateContainerResponse, error)

	// UpdateDevcontainerWithBodyWithResponse request with any body
	UpdateDevcontainerWithBodyWithResponse(ctx context.Context, cellId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDevcontainerResponse, error)

	UpdateDevcontainerWithResponse(ctx context.Context, cellId string, body UpdateDevcontainerJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDevcontainerResponse, error)

	// ResetContainerWithResponse request
	ResetContainerWithResponse(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*ResetContainerResponse, error)

	// RestartContainerWithResponse request
	RestartContainerWithResponse(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*RestartContainerResponse, error)

	// StartContainerWithResponse request
	StartContainerWithResponse(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*StartContainerResponse, error)

	// GetContainerStatusWithResponse request
	GetContainerStatusWithResponse(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*GetContainerStatusResponse, error)

	// StopContainerWithResponse request
	StopContainerWithResponse(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*StopContainerResponse, error)

	// ListCellFilesWithResponse request
	ListCellFilesWithResponse(ctx context.Context, cellId string, params *ListCellFilesParams, reqEditors ...RequestEditorFn) (*ListCellFilesResponse, error)

	// ReadCellFileWithResponse request
	ReadCellFileWithResponse(ctx context.Context, cellId string, filePath string, reqEditors ...RequestEditorFn) (*ReadCellFileResponse, error)

	// WriteCellFileWithBodyWithResponse request with any body
	WriteCellFileWithBodyWithResponse(ctx context.Context, cellId string, filePath string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*WriteCellFileResponse, error)

	WriteCellFileWithResponse(ctx context.Context, cellId string, filePath string, body WriteCellFileJSONRequestBody, reqEditors ...RequestEditorFn) (*WriteCellFileResponse, error)

	// CreateGitCommitWithBodyWithResponse request with any body
	CreateGitCommitWithBodyWithResponse(ctx context.Context, cellId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateGitCommitResponse, error)

	CreateGitCommitWithResponse(ctx context.Context, cellId string, body CreateGitCommitJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateGitCommitResponse, error)

	// GetGitDiffWithResponse request
	GetGitDiffWithResponse(ctx context.Context, cellId string, params *GetGitDiffParams, reqEditors ...RequestEditorFn) (*GetGitDiffResponse, error)

	// GetGitHistoryWithResponse request
	GetGitHistoryWithResponse(ctx context.Context, cellId string, params *GetGitHistoryParams, reqEditors ...RequestEditorFn) (*GetGitHistoryResponse, error)

	// GetGitStatusWithResponse request
	GetGitStatusWithResponse(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*GetGitStatusResponse, error)

	// GetGraphWithResponse request
	GetGraphWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetGraphResponse, error)

	// GetPositionsWithResponse request
	GetPositionsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetPositionsResponse, error)

	// SavePositionsWithBodyWithResponse request with any body
	SavePositionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SavePositionsResponse, error)

	SavePositionsWithResponse(ctx context.Context, body SavePositionsJSONRequestBody, reqEditors ...RequestEditorFn) (*SavePositionsResponse, error)
}

type CreateContainerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// ContainerId ID of the created container
		ContainerId *string `json:"containerId,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CreateContainerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateContainerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateDevcontainerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UpdateDevcontainerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateDevcontainerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ResetContainerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r ResetContainerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ResetContainerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RestartContainerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r RestartContainerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RestartContainerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StartContainerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r StartContainerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartContainerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetContainerStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// ContainerId Container ID (if exists)
		ContainerId *string `json:"containerId,omitempty"`

		// DevcontainerContent Content of the devcontainer.json file (if exists)
		DevcontainerContent *string `json:"devcontainerContent,omitempty"`

		// HasDevcontainer Whether a devcontainer.json file exists
		HasDevcontainer *bool `json:"hasDevcontainer,omitempty"`

		// Status Current container status
		Status *ContainerStatus `json:"status,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetContainerStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetContainerStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StopContainerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r StopContainerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StopContainerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListCellFilesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Files *[]FileInfo `json:"files,omitempty"`

		// Path The requested path
		Path *string `json:"path,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ListCellFilesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCellFilesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReadCellFileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r ReadCellFileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReadCellFileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type WriteCellFileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r WriteCellFileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WriteCellFileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateGitCommitResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r CreateGitCommitResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateGitCommitResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGitDiffResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetGitDiffResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGitDiffResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGitHistoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]GitCommit
}

// Status returns HTTPResponse.Status
func (r GetGitHistoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGitHistoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGitStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GitStatus
}

// Status returns HTTPResponse.Status
func (r GetGitStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGitStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGraphResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Graph
}

// Status returns HTTPResponse.Status
func (r GetGraphResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGraphResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPositionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Position
}

// Status returns HTTPResponse.Status
func (r GetPositionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPositionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SavePositionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r SavePositionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SavePositionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateContainerWithResponse request returning *CreateContainerResponse
func (c *ClientWithResponses) CreateContainerWithResponse(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*CreateContainerResponse, error) {
	rsp, err := c.CreateContainer(ctx, cellId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateContainerResponse(rsp)
}

// UpdateDevcontainerWithBodyWithResponse request with arbitrary body returning *UpdateDevcontainerResponse
func (c *ClientWithResponses) UpdateDevcontainerWithBodyWithResponse(ctx context.Context, cellId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDevcontainerResponse, error) {
	rsp, err := c.UpdateDevcontainerWithBody(ctx, cellId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDevcontainerResponse(rsp)
}

func (c *ClientWithResponses) UpdateDevcontainerWithResponse(ctx context.Context, cellId string, body UpdateDevcontainerJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDevcontainerResponse, error) {
	rsp, err := c.UpdateDevcontainer(ctx, cellId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDevcontainerResponse(rsp)
}

// ResetContainerWithResponse request returning *ResetContainerResponse
func (c *ClientWithResponses) ResetContainerWithResponse(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*ResetContainerResponse, error) {
	rsp, err := c.ResetContainer(ctx, cellId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResetContainerResponse(rsp)
}

// RestartContainerWithResponse request returning *RestartContainerResponse
func (c *ClientWithResponses) RestartContainerWithResponse(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*RestartContainerResponse, error) {
	rsp, err := c.RestartContainer(ctx, cellId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRestartContainerResponse(rsp)
}

// StartContainerWithResponse request returning *StartContainerResponse
func (c *ClientWithResponses) StartContainerWithResponse(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*StartContainerResponse, error) {
	rsp, err := c.StartContainer(ctx, cellId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartContainerResponse(rsp)
}

// GetContainerStatusWithResponse request returning *GetContainerStatusResponse
func (c *ClientWithResponses) GetContainerStatusWithResponse(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*GetContainerStatusResponse, error) {
	rsp, err := c.GetContainerStatus(ctx, cellId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetContainerStatusResponse(rsp)
}

// StopContainerWithResponse request returning *StopContainerResponse
func (c *ClientWithResponses) StopContainerWithResponse(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*StopContainerResponse, error) {
	rsp, err := c.StopContainer(ctx, cellId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStopContainerResponse(rsp)
}

// ListCellFilesWithResponse request returning *ListCellFilesResponse
func (c *ClientWithResponses) ListCellFilesWithResponse(ctx context.Context, cellId string, params *ListCellFilesParams, reqEditors ...RequestEditorFn) (*ListCellFilesResponse, error) {
	rsp, err := c.ListCellFiles(ctx, cellId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCellFilesResponse(rsp)
}

// ReadCellFileWithResponse request returning *ReadCellFileResponse
func (c *ClientWithResponses) ReadCellFileWithResponse(ctx context.Context, cellId string, filePath string, reqEditors ...RequestEditorFn) (*ReadCellFileResponse, error) {
	rsp, err := c.ReadCellFile(ctx, cellId, filePath, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReadCellFileResponse(rsp)
}

// WriteCellFileWithBodyWithResponse request with arbitrary body returning *WriteCellFileResponse
func (c *ClientWithResponses) WriteCellFileWithBodyWithResponse(ctx context.Context, cellId string, filePath string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*WriteCellFileResponse, error) {
	rsp, err := c.WriteCellFileWithBody(ctx, cellId, filePath, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWriteCellFileResponse(rsp)
}

func (c *ClientWithResponses) WriteCellFileWithResponse(ctx context.Context, cellId string, filePath string, body WriteCellFileJSONRequestBody, reqEditors ...RequestEditorFn) (*WriteCellFileResponse, error) {
	rsp, err := c.WriteCellFile(ctx, cellId, filePath, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWriteCellFileResponse(rsp)
}

// CreateGitCommitWithBodyWithResponse request with arbitrary body returning *CreateGitCommitResponse
func (c *ClientWithResponses) CreateGitCommitWithBodyWithResponse(ctx context.Context, cellId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateGitCommitResponse, error) {
	rsp, err := c.CreateGitCommitWithBody(ctx, cellId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateGitCommitResponse(rsp)
}

func (c *ClientWithResponses) CreateGitCommitWithResponse(ctx context.Context, cellId string, body CreateGitCommitJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateGitCommitResponse, error) {
	rsp, err := c.CreateGitCommit(ctx, cellId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateGitCommitResponse(rsp)
}

// GetGitDiffWithResponse request returning *GetGitDiffResponse
func (c *ClientWithResponses) GetGitDiffWithResponse(ctx context.Context, cellId string, params *GetGitDiffParams, reqEditors ...RequestEditorFn) (*GetGitDiffResponse, error) {
	rsp, err := c.GetGitDiff(ctx, cellId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGitDiffResponse(rsp)
}

// GetGitHistoryWithResponse request returning *GetGitHistoryResponse
func (c *ClientWithResponses) GetGitHistoryWithResponse(ctx context.Context, cellId string, params *GetGitHistoryParams, reqEditors ...RequestEditorFn) (*GetGitHistoryResponse, error) {
	rsp, err := c.GetGitHistory(ctx, cellId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGitHistoryResponse(rsp)
}

// GetGitStatusWithResponse request returning *GetGitStatusResponse
func (c *ClientWithResponses) GetGitStatusWithResponse(ctx context.Context, cellId string, reqEditors ...RequestEditorFn) (*GetGitStatusResponse, error) {
	rsp, err := c.GetGitStatus(ctx, cellId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGitStatusResponse(rsp)
}

// GetGraphWithResponse request returning *GetGraphResponse
func (c *ClientWithResponses) GetGraphWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetGraphResponse, error) {
	rsp, err := c.GetGraph(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGraphResponse(rsp)
}

// GetPositionsWithResponse request returning *GetPositionsResponse
func (c *ClientWithResponses) GetPositionsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetPositionsResponse, error) {
	rsp, err := c.GetPositions(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPositionsResponse(rsp)
}

// SavePositionsWithBodyWithResponse request with arbitrary body returning *SavePositionsResponse
func (c *ClientWithResponses) SavePositionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SavePositionsResponse, error) {
	rsp, err := c.SavePositionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSavePositionsResponse(rsp)
}

func (c *ClientWithResponses) SavePositionsWithResponse(ctx context.Context, body SavePositionsJSONRequestBody, reqEditors ...RequestEditorFn) (*SavePositionsResponse, error) {
	rsp, err := c.SavePositions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSavePositionsResponse(rsp)
}

// ParseCreateContainerResponse parses an HTTP response from a CreateContainerWithResponse call
func ParseCreateContainerResponse(rsp *http.Response) (*CreateContainerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateContainerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// ContainerId ID of the created container
			ContainerId *string `json:"containerId,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUpdateDevcontainerResponse parses an HTTP response from a UpdateDevcontainerWithResponse call
func ParseUpdateDevcontainerResponse(rsp *http.Response) (*UpdateDevcontainerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateDevcontainerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseResetContainerResponse parses an HTTP response from a ResetContainerWithResponse call
func ParseResetContainerResponse(rsp *http.Response) (*ResetContainerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ResetContainerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseRestartContainerResponse parses an HTTP response from a RestartContainerWithResponse call
func ParseRestartContainerResponse(rsp *http.Response) (*RestartContainerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RestartContainerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseStartContainerResponse parses an HTTP response from a StartContainerWithResponse call
func ParseStartContainerResponse(rsp *http.Response) (*StartContainerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartContainerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetContainerStatusResponse parses an HTTP response from a GetContainerStatusWithResponse call
func ParseGetContainerStatusResponse(rsp *http.Response) (*GetContainerStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetContainerStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// ContainerId Container ID (if exists)
			ContainerId *string `json:"containerId,omitempty"`

			// DevcontainerContent Content of the devcontainer.json file (if exists)
			DevcontainerContent *string `json:"devcontainerContent,omitempty"`

			// HasDevcontainer Whether a devcontainer.json file exists
			HasDevcontainer *bool `json:"hasDevcontainer,omitempty"`

			// Status Current container status
			Status *ContainerStatus `json:"status,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseStopContainerResponse parses an HTTP response from a StopContainerWithResponse call
func ParseStopContainerResponse(rsp *http.Response) (*StopContainerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StopContainerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseListCellFilesResponse parses an HTTP response from a ListCellFilesWithResponse call
func ParseListCellFilesResponse(rsp *http.Response) (*ListCellFilesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCellFilesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Files *[]FileInfo `json:"files,omitempty"`

			// Path The requested path
			Path *string `json:"path,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseReadCellFileResponse parses an HTTP response from a ReadCellFileWithResponse call
func ParseReadCellFileResponse(rsp *http.Response) (*ReadCellFileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReadCellFileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseWriteCellFileResponse parses an HTTP response from a WriteCellFileWithResponse call
func ParseWriteCellFileResponse(rsp *http.Response) (*WriteCellFileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WriteCellFileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCreateGitCommitResponse parses an HTTP response from a CreateGitCommitWithResponse call
func ParseCreateGitCommitResponse(rsp *http.Response) (*CreateGitCommitResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateGitCommitResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetGitDiffResponse parses an HTTP response from a GetGitDiffWithResponse call
func ParseGetGitDiffResponse(rsp *http.Response) (*GetGitDiffResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGitDiffResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetGitHistoryResponse parses an HTTP response from a GetGitHistoryWithResponse call
func ParseGetGitHistoryResponse(rsp *http.Response) (*GetGitHistoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGitHistoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []GitCommit
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetGitStatusResponse parses an HTTP response from a GetGitStatusWithResponse call
func ParseGetGitStatusResponse(rsp *http.Response) (*GetGitStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGitStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GitStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetGraphResponse parses an HTTP response from a GetGraphWithResponse call
func ParseGetGraphResponse(rsp *http.Response) (*GetGraphResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGraphResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Graph
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetPositionsResponse parses an HTTP response from a GetPositionsWithResponse call
func ParseGetPositionsResponse(rsp *http.Response) (*GetPositionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPositionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Position
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSavePositionsResponse parses an HTTP response from a SavePositionsWithResponse call
func ParseSavePositionsResponse(rsp *http.Response) (*SavePositionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SavePositionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcfXPbNtL/Khj2mXmcCS1Rfkn7aCbT5LET1526zdjJ9e7i/AGRKwktCTAAKFuX8Xe/",
	"wRtfRJCm5OYap/dPIgnAAtjd3+4Ci/WnIGZZzihQKYLpp0DES8iw/ngCaar+zznLgUsC+tcEcqAJ0Lj8",
	"LmJOckkYDabBT0RIxOYohjRF56cCySUR5psZKBCjQRgQCZkeLtc5BNNASE7oIrgL3Q+Yc7xW30nSnuUd",
	"JR8LQCQBKsmcAEdzxpFcgp4pCNtUKc6gTeeUiDzFa6Ra1ar7KORYLtsUXpMUkFgLCRlSPZBkJRWUEA6x",
	"ZHzto2d+2KT3dp1Dyb89GC1GIcpYUqQQopTMOObrJ21qd2HA4WNBOCTB9L1imd2xXbYdEDaF96Gkw2a/",
	"QSzVqk4YlZhQ4FcSy8Ij4JOCc6ASxa4jEqZnGAAtMjU9ZVTNJSTLc1BL4QWlap1hAJwzXpu4YserZAFt",
	"ZdtO+KBoeGgLVvDYw+wTo6RO8qYb2ptzlj3xigzzBch76ZhuaE+ygaKy6ysn8AlGKdo5nTMPj8Qp4e1F",
	"/boEuQRuAEgEwj51nDGWAqbdCNH6zXg1Flm9GoiPS0ixJCsw4FCcHQANQf7VtRTVhAhFs7UEgfYiLXtH",
	"jIBQHJ8znmEZTANC5bOjagJCJSyAd4NPzyA1Ajm6OL94hSxs+mXYRJoRh92EHeoT6BmRJyzLiGxLFBdy",
	"yTwiNf2RaTZGC9MEQYaJ12QlWEInFUkyEBJneZ1jasS+avGRW2Lhs4BFmqLY0NQ9PCMzEAIvutfi2n26",
	"sGRc/uCd+eVsxmFFsISkfwEb8rKdKsqh47hlWbXgDsFVxnFDcEvAHov1c5HNgGuzrpcpkO6ofuCQMQle",
	"HZ3BktBB1EzPXloc03jZbc3PiESmTye+Y20oeswMoBvGfyd0UTMWyvfrcT6LMydpXwiRsUSZ9wSZfrWY",
	"4X84zINp8M24Cl3GNm4Zl9JRYPbFE0ssLg2jOveCLSv18hmdk0XBtSPb3MOGYlkuO165HYZWL0qR1hfR",
	"q2F6Dy0t64lEtJXlzuZKhjjkTBAtC86Y9CKsw9MrnTBtKGYJoL2L504kIXr5HCeJ+nD6PIEUpPr4/fOC",
	"So7j39UXkPHoSS0ouAjC4GUQBqdBGHwfhMFlEAYnQRi880QDG2y1htWu08swjvNlm1HK0/QoGFaGS3VR",
	"DkXp70KTGahoOjr26JcKQu6ZVHdBe/Vg7MlOa9BBU2sNG+wzXHAL87HvjVIRvUwfB889NqgKdrQ31zFG",
	"bqmgGaSMLgSSzKdut21qf0cxYzwhFEtwfHh33vBLrJilNbNEtQ1U5NZtcv/YmZyHc+cKrreBmqjNOjWA",
	"2KBswze9OdehSYYpXiibaBRtb8ZuQTwJ1ZoIN5YtRAsikeI6VoNFqJ16GV+X2vk3MoO3itE4z1MS685q",
	"C0QqIxGUzS/fqL2ugAuzlMkoGkWKVSwHinMSTIPDUTQ6tCGLlvMY52Sslzj+ZHZ9Ny5XMI452EgiZ8IX",
	"/+p2FWJSuEEJrKrDgQvNRQ6xseb2fFXuV6mXpVAePvTSOM5AAhfB9H2/+im0qF+tnTCBbCW8SqKSFxDa",
	"E67n7Hn3QXUWOaPCaP9BFGkQMCqB6n3XWD/+TRjEwC3OcmOny33rTeFZPDk4TGB+dPxMG9py4g2Q1Uf1",
	"bFXzqKYZ3kDHo6GbIZeTjSMoijgGIeZFmmoLdhQdbWxbwq0c5ykmzQ2bgw9lEs1Zof1aN2/b62iOvQuD",
	"4xa7vfManum1v9LHyemnYIXTQk33GpMUEuX4TIcas5QA8KpviGqunWvPTzVDt9hS3+yKUpFlmK9LdW9K",
	"Ei+UplfiCT6oMf3ArENN61XhQee7PNHoZE7iQqtTfexI6bK2Rhqw2A9SQ+i0PuefiNOPBQj5/yxZD4Bo",
	"H/LssObCf7z65WdkW0sb5ufYvccNN4nffTR3fee3QBu3VnUD6+JTvWFUaBH5IN0PrS2U/JyucErUaUNL",
	"AM1Ysla6VWfZECvyWU3FTqA1zGv6rwZ7N1D87t7+O8KagzDXTH53q04OK+1uq3l1yJACVuGCOl8KwWJi",
	"dOKGyGUdg01QX6q5vlDH2+W4NH8e4rZKSrv6Lg+BLR2YOTX1eCPTYcMfKT4p4feMMx02Xc8ueDBs7vJh",
	"lxutu+u6xLxX23WHhrr7tFh1enx6rFb9sBDsT9LlXTVKbbhPpzbad9Sqe3TqymoURXBLhNTns07dunqE",
	"mvUX06t+rbr6w3TK3pN5k0CXIDmBlY2u7cUZmze9tHXLkBiv3BFon9U88pXLrj26A7EeQdlJ/YBi3dWn",
	"8tLRJAt1IGyShP7uPQfr6gKzzDPe3e162j6peVu0R+bGPghvNrAe9510HSRsg5NOx6HrnpmWWJxunPS6",
	"Lq47JjDEvbfwlVr33nZu6OOgq4armvVB3OIjaaeOP5dZWIAnT920DWfgTWXvaCBY3udzWK6CGKukvQ6H",
	"5Y/O3+hc/1/H37C8x900GrdSpjIl5nUxPykQ6wyC7qcPfbXct/YphFqv8r+ikWRvqpiipE7Vr22C6s9Q",
	"sbCFkGJWZQ51JstuqMwz7DHdF6dP3Co+FqC3Z5fhUkWf74rXSuh9+e5ijlMB5QIuX708vXg1yhL3IKD5",
	"k3nZMIkOjkrzqdUxw/z3hN0og1wSNvyzdAWPK4rmi6EVlYQqaatd2q59986lsg3KNZUPUDw5L39G8u0S",
	"3C0RJKj+EGm7G+sON6IdW0qE/JLvrLe6WJPAKU6RAL4CjsxbqaZt0VlEA35CPS9prKUxsO63MuNP6r83",
	"WC7vemJanJh4Nq7iGOySObERwXCro8g5q/OlGJ03tUd7ejv17HmLwZ5FOC7+wYF1l/p+g16Zz0gn/G18",
	"eU3f2mdeG8Jy2xpd0+1UfQN02OJtiwveRwC5+s2E3WHrRmJz522UhYPzLrhCjE6VOkENh9CvnEj4L4Z2",
	"ygJtJGp1z+Ab9M7mTLrxVBeVSwY5UN1z0vQeCt/WMCoZulEyrfPvP59S0ntX65BAt04e1c/7xGSHnER8",
	"19O4mTvSb7zNqB+toNwol2rSqSXTd7u7bF+u6qszXUZ9PLbr17Khx3h1hAgLIsdx9Tx1wLOPMyLdK0xt",
	"31yobhYgpH4G0/Hwo3oL+0gSyp4DQWBSf/rSRekJSEnoQozWOEsVUMs3sC5v2MzcGjJDovUmR35xbE7t",
	"AzMTHZpL0QWgGcwZBysZaUQwvPhi54e7Gwar+z3tjgbLzt/9hGVrk9VnfDQriBCELi4qjrieTV4op1Fu",
	"6GH26qszVeWzGI1175uYyozUjNUZkf2mKiHz+cCbedVV4aSgFhOQoHiJ6cKcqQbEYGcgz4g8VVN+IQFY",
	"+QibIbFkNwb61bYYTdcdFyamZ0NZEpjjIpXlzUbr0fPuhxfN+/39BZEI61PoSN5KNCs/XlNCE7hFk4PD",
	"o+Nn345GeBYnMF+gSRQ9Ozq6pvv7+7WR1/Tp06eN4S9eoP1JeIieqn9evLim+7+kCUoJhWv69Ge4sR/R",
	"O2p449oedDZyFxJaCb82yC5A2o217s0VVBODgsFAXRKhMTUMq66qwwyqvU0bgM8f7ExfCEQv8C3JigzR",
	"VvWGDorNrjtAmhJjDj0YPY6UZ6KKdDCdtEs/Hnrh+b6qRgp+ZEuKThmg6yKKDuPf2JK+sB1HMcv0r+Bq",
	"aKbBQXRwtB9N9ifHbyfR9DCaRtE/A1dFFODJ7CA+TI7geP7s2+/+L7KQb3xS6A/qkdPLJNGx5hywLDg0",
	"inhKkvoOtVo0poCuMhWR2mVjCoOWffR2cjw9Om4u+/5FT7TNaiz7NblFs2Kh3Iup5dxYuCWq720rGQ8t",
	"d7GRc7sMYHg+ro6yr9KClXvzGrENBmxhzrZ6E1ArqNnKkj3eJwC1mriDqqAtqurRgkxJtiwusxFHlWOx",
	"WQxXd6ScfD3hf6GxbjtRuNl3kUC90/caV7WyL3vIqPY8qJ5sC0BVgv4qwVTfnhdPrTR6E0cLV601LALI",
	"9TtIPQgJyYtYmf5m/Ramia2oaRS4++Bky6seWOdhCsveb/41BFMydKAUGtL0UB13SWJxN6lg6G7wTwxQ",
	"rf6O1f9jycautxWLdRkmpGjMVid/UJF/SZk+DfSQP6jI278qoEFia9fem8J7/XVS1adX+3CF8HZmnbR0",
	"Aw7uHXAY3H0Yjj8tsOHYM8o1/DFuQ7tnBUktianJv+n7ykZNa7Dja9oabe8bFKvnpYjXZSlgiSL9vcKR",
	"K7gb4n8EVsxZEVHgtKzUs37IWwZpKuZa+HlTzvnguNLVFpZKchtMJ1GkS/oOokgpVaPLgelyaLscRdEO",
	"8VJZ6rh7uFSx/XMa2dosbWVRtj6vScJpSCUdnZXyv0PCK5OUKmx+yqsUwxRC0WpqxE6XqF+mMuxwK1ny",
	"wuLtIdeSkOVyvZlHuawX3TQuGsNh95gPz5+4Wp/P97gKr6BT/a90jd4Q/dfj9EsKX7T8E4txihJYQcry",
	"DKi0ry6CMCh4GkyDpZT5dDxOVb8lE3L6XfRdpJ2knax9Ee8KeE3602zGPPpsmXTrqa1zC3totYqIa0Ct",
	"1zZbim9qxqnvbxVV5cYu+dzI05roydJ8bVMTvj8QUPv7Aqy5aFd27raqj6ieUrbq3V5K5hCv4xTMhiEz",
	"GStLoHo9d/fh7t8BAAD//8JF03G2SgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
