# Global Go tasks
$schema: '../cache/schemas/global-tasks.json'

tasks:
  build:
    command: 'go build ./...'
    inputs:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    platform: 'system'
    deps:
      - "^:build"
    options:
      runInCI: true
      outputStyle: stream

  test:
    command: 'gotestsum -- -v ./...'
    deps:
      - "^:build"
    inputs:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    platform: 'system'
    options:
      runInCI: true
      outputStyle: stream

  lint:
    command: 'go vet ./...'
    inputs:
      - '**/*.go'
    platform: 'system'
    options:
      runInCI: true
  tidy:
    command: 'go mod tidy'
    deps:
      - "^:tidy"
    inputs:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    platform: 'system'
