# Global Go tasks
$schema: '../cache/schemas/global-tasks.json'

tasks:
  build:
    command: 'go build ./...'
    inputs:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    deps:
      - "^:build"
    options:
      runInCI: true
      outputStyle: buffer-only-failure

  test:
    command: 'go test -v ./...'
    deps:
      - "^:build"
    inputs:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    options:
      runInCI: true
      outputStyle: buffer-only-failure

  lint:
    command: 'go vet ./...'
    inputs:
      - '**/*.go'
    options:
      runInCI: true
  tidy:
    command: 'go mod tidy'
    deps:
      - "^:tidy"
    inputs:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    options:
      runInCI: true
      outputStyle: buffer-only-failure
