# .moon/tasks/node.yml
$schema: '../cache/schemas/global-tasks.json'

fileGroups:
  sources:
    - 'src/**/*'

  # absolute path (leading slash) → resolved from workspace root
  lockfile:
    - 'package-lock.json'

  config:
    - 'vite.config.[jt]s'
    - 'tsconfig.json'
    - 'package.json'

tasks:
  build:
    command: vite
    args: [build, --logLevel, warn]
    inputs:
      - '@group(sources)'
      - '@group(config)'
      - '@group(lockfile)'      # ← hash the real lock-file
    outputs:
      - dist/
    deps:
      - "^:build"
    platform: node
    options:
      runInCI: true

  test:
    command: npx
    args: [vitest, run, --reporter=dot]
    deps:
      - "^:build"
    inputs:
      - '@group(sources)'
      - tests/**/*
      - '@group(config)'
      - '@group(lockfile)'
    platform: node
    options:
      runInCI: true

  lint:
    command: eslint
    args: [src]
    inputs:
      - '@group(sources)'
      - .eslintrc*
      - '@group(lockfile)'
    platform: node
    options:
      runInCI: true
