// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package openapi

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for FieldType.
const (
	FieldTypeCheckboxGrid       FieldType = "checkbox_grid"
	FieldTypeCheckboxes         FieldType = "checkboxes"
	FieldTypeDate               FieldType = "date"
	FieldTypeDropdown           FieldType = "dropdown"
	FieldTypeFileUpload         FieldType = "file_upload"
	FieldTypeLinearScale        FieldType = "linear_scale"
	FieldTypeMultipleChoice     FieldType = "multiple_choice"
	FieldTypeMultipleChoiceGrid FieldType = "multiple_choice_grid"
	FieldTypeParagraphText      FieldType = "paragraph_text"
	FieldTypeShortAnswer        FieldType = "short_answer"
	FieldTypeTime               FieldType = "time"
)

// Defines values for InputSSEEventType.
const (
	Connected      InputSSEEventType = "connected"
	Error          InputSSEEventType = "error"
	Heartbeat      InputSSEEventType = "heartbeat"
	InputCancelled InputSSEEventType = "input_cancelled"
	InputPending   InputSSEEventType = "input_pending"
)

// Artifact defines model for Artifact.
type Artifact struct {
	Path string `json:"path"`
}

// CancelRequest defines model for CancelRequest.
type CancelRequest struct {
	// Reason Human-readable cancellation reason
	Reason *string `json:"reason,omitempty"`
}

// FieldType defines model for FieldType.
type FieldType string

// FieldValidation defines model for FieldValidation.
type FieldValidation struct {
	Max       *int    `json:"max,omitempty"`
	MaxLength *int    `json:"max_length,omitempty"`
	Min       *int    `json:"min,omitempty"`
	MinLength *int    `json:"min_length,omitempty"`
	Pattern   *string `json:"pattern,omitempty"`
}

// FormContext defines model for FormContext.
type FormContext struct {
	Artifacts           *[]Artifact    `json:"artifacts,omitempty"`
	ArtifactsFromOutput *string        `json:"artifacts_from_output,omitempty"`
	ArtifactsGlob       *[]GlobPattern `json:"artifacts_glob,omitempty"`
}

// FormField defines model for FormField.
type FormField struct {
	Id          string           `json:"id"`
	Options     *[]Option        `json:"options,omitempty"`
	Placeholder *string          `json:"placeholder,omitempty"`
	Question    string           `json:"question"`
	Required    *bool            `json:"required,omitempty"`
	Scale       *LinearScale     `json:"scale,omitempty"`
	Type        FieldType        `json:"type"`
	Validation  *FieldValidation `json:"validation,omitempty"`
}

// FormResponse defines model for FormResponse.
type FormResponse struct {
	ActivityId *string `json:"activity_id,omitempty"`

	// Fields Field responses for multi-field forms
	Fields map[string]interface{} `json:"fields"`
	Hash   *string                `json:"hash,omitempty"`

	// Response Single-question response value
	Response       *interface{} `json:"response,omitempty"`
	SubmittedAt    *time.Time   `json:"submitted_at,omitempty"`
	TimeToComplete *int         `json:"time_to_complete,omitempty"`
	UserId         *string      `json:"user_id,omitempty"`
}

// GlobPattern defines model for GlobPattern.
type GlobPattern struct {
	Pattern string `json:"pattern"`
}

// InputFormConfig Configuration for a single- or multi-question input form.
type InputFormConfig struct {
	Context *FormContext `json:"context,omitempty"`

	// DefaultOnTimeout Default value to return if input times out
	DefaultOnTimeout *interface{} `json:"default_on_timeout,omitempty"`
	Fields           *[]FormField `json:"fields,omitempty"`
	Options          *[]Option    `json:"options,omitempty"`
	Question         *string      `json:"question,omitempty"`
	Scale            *LinearScale `json:"scale,omitempty"`

	// Timeout Timeout in seconds
	Timeout *int       `json:"timeout,omitempty"`
	Title   *string    `json:"title,omitempty"`
	Type    *FieldType `json:"type,omitempty"`
}

// InputSSECancelledData defines model for InputSSECancelledData.
type InputSSECancelledData struct {
	JobId  string  `json:"jobId"`
	Reason *string `json:"reason,omitempty"`
}

// InputSSEConnectedData defines model for InputSSEConnectedData.
type InputSSEConnectedData struct {
	ClientId string `json:"client_id"`
}

// InputSSEErrorData defines model for InputSSEErrorData.
type InputSSEErrorData struct {
	Error string `json:"error"`
}

// InputSSEEvent Event envelope emitted by /api/projects/{projectId}/user-inputs/stream.
type InputSSEEvent struct {
	Data InputSSEEvent_Data `json:"data"`

	// Type Input SSE event type emitted by /api/projects/{projectId}/user-inputs/stream.
	Type InputSSEEventType `json:"type"`
}

// InputSSEEvent_Data defines model for InputSSEEvent.Data.
type InputSSEEvent_Data struct {
	union json.RawMessage
}

// InputSSEEventType Input SSE event type emitted by /api/projects/{projectId}/user-inputs/stream.
type InputSSEEventType string

// InputSSEHeartbeatData defines model for InputSSEHeartbeatData.
type InputSSEHeartbeatData struct {
	Timestamp time.Time `json:"timestamp"`
}

// InputSSEPendingData defines model for InputSSEPendingData.
type InputSSEPendingData struct {
	// Id Workflow job ID
	Id string `json:"id"`
}

// LinearScale defines model for LinearScale.
type LinearScale struct {
	Max      int     `json:"max"`
	MaxLabel *string `json:"max_label,omitempty"`
	Min      int     `json:"min"`
	MinLabel *string `json:"min_label,omitempty"`
}

// OkResponse defines model for OkResponse.
type OkResponse struct {
	Ok *bool `json:"ok,omitempty"`
}

// Option defines model for Option.
type Option struct {
	Label *string `json:"label,omitempty"`
	Value string  `json:"value"`
}

// PendingInput defines model for PendingInput.
type PendingInput struct {
	// Id Workflow job ID
	Id string `json:"id"`
}

// UserInputDetails defines model for UserInputDetails.
type UserInputDetails struct {
	// Form Configuration for a single- or multi-question input form.
	Form      InputFormConfig `json:"form"`
	Hash      *string         `json:"hash,omitempty"`
	JobId     string          `json:"jobId"`
	StartTime time.Time       `json:"startTime"`
	Status    string          `json:"status"`
}

// PostApiProjectsProjectIdUserInputsJobIdCancelJSONRequestBody defines body for PostApiProjectsProjectIdUserInputsJobIdCancel for application/json ContentType.
type PostApiProjectsProjectIdUserInputsJobIdCancelJSONRequestBody = CancelRequest

// PostApiProjectsProjectIdUserInputsJobIdRespondJSONRequestBody defines body for PostApiProjectsProjectIdUserInputsJobIdRespond for application/json ContentType.
type PostApiProjectsProjectIdUserInputsJobIdRespondJSONRequestBody = FormResponse

// AsInputSSEConnectedData returns the union data inside the InputSSEEvent_Data as a InputSSEConnectedData
func (t InputSSEEvent_Data) AsInputSSEConnectedData() (InputSSEConnectedData, error) {
	var body InputSSEConnectedData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInputSSEConnectedData overwrites any union data inside the InputSSEEvent_Data as the provided InputSSEConnectedData
func (t *InputSSEEvent_Data) FromInputSSEConnectedData(v InputSSEConnectedData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInputSSEConnectedData performs a merge with any union data inside the InputSSEEvent_Data, using the provided InputSSEConnectedData
func (t *InputSSEEvent_Data) MergeInputSSEConnectedData(v InputSSEConnectedData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInputSSEPendingData returns the union data inside the InputSSEEvent_Data as a InputSSEPendingData
func (t InputSSEEvent_Data) AsInputSSEPendingData() (InputSSEPendingData, error) {
	var body InputSSEPendingData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInputSSEPendingData overwrites any union data inside the InputSSEEvent_Data as the provided InputSSEPendingData
func (t *InputSSEEvent_Data) FromInputSSEPendingData(v InputSSEPendingData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInputSSEPendingData performs a merge with any union data inside the InputSSEEvent_Data, using the provided InputSSEPendingData
func (t *InputSSEEvent_Data) MergeInputSSEPendingData(v InputSSEPendingData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInputSSECancelledData returns the union data inside the InputSSEEvent_Data as a InputSSECancelledData
func (t InputSSEEvent_Data) AsInputSSECancelledData() (InputSSECancelledData, error) {
	var body InputSSECancelledData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInputSSECancelledData overwrites any union data inside the InputSSEEvent_Data as the provided InputSSECancelledData
func (t *InputSSEEvent_Data) FromInputSSECancelledData(v InputSSECancelledData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInputSSECancelledData performs a merge with any union data inside the InputSSEEvent_Data, using the provided InputSSECancelledData
func (t *InputSSEEvent_Data) MergeInputSSECancelledData(v InputSSECancelledData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInputSSEHeartbeatData returns the union data inside the InputSSEEvent_Data as a InputSSEHeartbeatData
func (t InputSSEEvent_Data) AsInputSSEHeartbeatData() (InputSSEHeartbeatData, error) {
	var body InputSSEHeartbeatData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInputSSEHeartbeatData overwrites any union data inside the InputSSEEvent_Data as the provided InputSSEHeartbeatData
func (t *InputSSEEvent_Data) FromInputSSEHeartbeatData(v InputSSEHeartbeatData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInputSSEHeartbeatData performs a merge with any union data inside the InputSSEEvent_Data, using the provided InputSSEHeartbeatData
func (t *InputSSEEvent_Data) MergeInputSSEHeartbeatData(v InputSSEHeartbeatData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInputSSEErrorData returns the union data inside the InputSSEEvent_Data as a InputSSEErrorData
func (t InputSSEEvent_Data) AsInputSSEErrorData() (InputSSEErrorData, error) {
	var body InputSSEErrorData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInputSSEErrorData overwrites any union data inside the InputSSEEvent_Data as the provided InputSSEErrorData
func (t *InputSSEEvent_Data) FromInputSSEErrorData(v InputSSEErrorData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInputSSEErrorData performs a merge with any union data inside the InputSSEEvent_Data, using the provided InputSSEErrorData
func (t *InputSSEEvent_Data) MergeInputSSEErrorData(v InputSSEErrorData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t InputSSEEvent_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *InputSSEEvent_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
