package recipe

import (
	"context"
	"errors"
	"fmt"

	coreops "github.com/colony-2/colony2/server/recipe-core/pkg/ops"
	"github.com/colony-2/colony2/server/recipe-core/pkg/workflowctl"
)

// ResetChildWorkflowActivityName is the registered Temporal activity name used by recipe-worker.
const ResetChildWorkflowActivityName = "_internal.recipe.reset_child_workflow"

// ResetChildWorkflowActivityInput captures the reset parameters provided by the parent workflow.
type ResetChildWorkflowActivityInput struct {
	WorkflowID        string `json:"workflow_id"`
	RunID             string `json:"run_id"`
	EventID           int64  `json:"event_id"`
	Reason            string `json:"reason,omitempty"`
	WaitForCompletion bool   `json:"wait_for_completion"`
}

// ResetChildWorkflowActivityResult reports the run id generated by the reset and, when requested,
// the unserialized workflow result.
type ResetChildWorkflowActivityResult struct {
	RunID     string                 `json:"run_id"`
	Completed bool                   `json:"completed"`
	Result    map[string]interface{} `json:"result,omitempty"`
}

// ResetChildWorkflowActivity performs workflow resets using the runtime dependencies supplied by recipe-worker.
type ResetChildWorkflowActivity struct {
	deps coreops.ServiceDependencies2
}

// NewResetChildWorkflowActivity creates a new reset activity bound to the provided dependencies.
func NewResetChildWorkflowActivity(deps coreops.ServiceDependencies2) *ResetChildWorkflowActivity {
	return &ResetChildWorkflowActivity{deps: deps}
}

func (a *ResetChildWorkflowActivity) Execute(ctx context.Context, input ResetChildWorkflowActivityInput) (ResetChildWorkflowActivityResult, error) {
	if input.WorkflowID == "" {
		return ResetChildWorkflowActivityResult{}, errors.New("workflow_id is required")
	}
	if input.RunID == "" {
		return ResetChildWorkflowActivityResult{}, errors.New("run_id is required")
	}
	if input.EventID <= 0 {
		return ResetChildWorkflowActivityResult{}, errors.New("event_id must be positive")
	}
	if a == nil || a.deps == nil {
		return ResetChildWorkflowActivityResult{}, errors.New("dependencies not configured")
	}

	ctl, ok := a.deps.WorkflowControl()
	if !ok || ctl == nil {
		return ResetChildWorkflowActivityResult{}, errors.New("workflow control dependency not available")
	}

	resp, err := ctl.ResetWorkflow(ctx, workflowctl.ResetRequest{
		Execution: workflowctl.ExecutionRef{
			WorkflowID: input.WorkflowID,
			RunID:      input.RunID,
		},
		WorkflowTaskFinishEventID: input.EventID,
		Reason:                    input.Reason,
		WaitForResult:             input.WaitForCompletion,
	})
	if err != nil {
		return ResetChildWorkflowActivityResult{}, err
	}

	result := ResetChildWorkflowActivityResult{RunID: resp.Execution.RunID}
	if input.WaitForCompletion {
		if !resp.Completed {
			return ResetChildWorkflowActivityResult{}, fmt.Errorf("reset response missing completion payload for %s/%s", resp.Execution.WorkflowID, resp.Execution.RunID)
		}
		payload := resp.Result
		if payload == nil {
			payload = make(map[string]interface{})
		}
		result.Completed = true
		result.Result = payload
	}
	return result, nil
}
